### PR TITLE
UX Audit: Fix individual post and gear review pages

### LINKED ISSUE #212: UX Audit: Individual Post & Gear Review Pages
<html><head></head><body><p>Clear patterns across both content types. Here's a full audit:</p>
<hr>
<h2>UX Audit: Individual Post &amp; Gear Review Pages</h2>
<hr>
<h3>🔴 Critical: Content Column Is Far Too Narrow</h3>
<p><strong>Images 3, 4, 5</strong></p>
<p>The article body wraps at roughly 550px while the viewport is ~1200px. This leaves the entire right half of the page as empty white space. This is the single most damaging layout issue on the detail pages.</p>
<p><strong>Fix:</strong></p>
<pre><code class="language-css">.article-body {
  max-width: 720px;   /* industry standard for readable prose */
  width: 100%;
  margin: 0 auto;     /* center it within the content area */
}
</code></pre>
<p>720px is the sweet spot — wide enough to feel spacious, narrow enough to maintain ~75 characters per line for readable prose. The current ~550px is causing cramped, short lines that feel like a mobile view on desktop.</p>
<hr>
<h3>🔴 Critical: Gear Review Scores Are Empty (Image 1)</h3>
<p><strong>Durability</strong> and <strong>Value</strong> both render <code>—</code> instead of a star rating. Only "Overall" shows a value (5). This means the rating data is either missing from the content model or the component is failing silently.</p>
<p><strong>Fix — two-part:</strong></p>
<pre><code>1. Data: Ensure durability/value fields are required in the 
   content schema with a fallback of 0, not null/undefined

2. Component: Never render a label with no value. Either:
   - Show "N/A" in muted text
   - Hide the row entirely with: {value &amp;&amp; &lt;RatingRow /&gt;}
   - Show empty stars (☆☆☆☆☆) rather than a dash
</code></pre>
<hr>
<h3>🔴 Critical: "Where to Buy" Box Is Completely Empty (Images 1, 2)</h3>
<p>The affiliate link container renders as a blank white box with only an external link icon in the corner. No store name, no product name, no URL visible.</p>
<p><strong>Fix:</strong></p>
<pre><code class="language-jsx">// Guard against empty link data
{buyLink?.url ? (
  &lt;a href={buyLink.url} className="buy-link-card"&gt;
    &lt;span&gt;{buyLink.label || buyLink.url}&lt;/span&gt;
    &lt;ExternalLinkIcon /&gt;
  &lt;/a&gt;
) : (
  // Don't render the section at all if no link exists
  null
)}
</code></pre>
<p>Hide the entire "WHERE TO BUY" section if there's no link data — a blank box actively harms credibility.</p>
<hr>
<h3>🟠 Major: "NO SPECS PROVIDED" Is Displayed Prominently (Image 1)</h3>
<p>This reads as a broken or incomplete page to a visitor. Empty state messages meant for CMS editors are leaking into production.</p>
<p><strong>Fix:</strong></p>
<pre><code class="language-jsx">// Only render the section if specs exist
{specs?.length &gt; 0 &amp;&amp; (
  &lt;section&gt;
    &lt;h2&gt;TECHNICAL SPECS&lt;/h2&gt;
    &lt;SpecsTable data={specs} /&gt;
  &lt;/section&gt;
)}
</code></pre>
<p>Never show a section whose only content is "nothing here."</p>
<hr>
<h3>🟠 Major: Author Avatar Is a Broken Black Square (Images 3, 5)</h3>
<p>The author photo area renders as a solid dark rectangle — the image failed to load with no fallback.</p>
<p><strong>Fix:</strong></p>
<pre><code class="language-jsx">&lt;img 
  src={author.avatar} 
  alt={author.name}
  onError={(e) =&gt; {
    e.target.style.display = 'none';
    // Show initials fallback
  }}
/&gt;
// OR CSS fallback:
.author-avatar {
  background: #1a2332;  /* matches current dark color */
  /* Show initials via ::after or a &lt;span&gt; sibling */
}
</code></pre>
<p>Use an initials-based fallback — "AA" for Ariel Anders — styled as a circle in the brand color.</p>
<hr>
<h3>🟠 Major: "IN THIS POST" Has No Actual Table of Contents (Images 3, 5)</h3>
<p>The label "IN THIS POST" appears above a divider but is followed immediately by the article content — there's no list of anchor links. The TOC either failed to generate or was never implemented.</p>
<p><strong>Fix:</strong></p>
<pre><code>Option A (quick): Remove "IN THIS POST" entirely until TOC is built
Option B (proper): Auto-generate from h2/h3 headings:

  IN THIS POST
  ─────────────────────
  → Kill the Vercel Build Grind
  → 1. Stop Vercel from Building
  → 2. Set GitHub to Action Mode
  → 3. Build the Multi-Branch Workflow
  → 4. Get Instant Feedback
</code></pre>
<hr>
<h3>🟠 Major: Related Posts Inherits the Broken Empty Card Bug (Images 4, 5)</h3>
<p>The "RELATED POSTS" section at the bottom uses the same oversized card component with a giant blank image area — same bug as the index pages, now also appearing in the detail view.</p>
<p><strong>Fix:</strong> Same as previous audit — cap the image zone height and use a skeleton or category-color strip instead of a blank placeholder icon.</p>
<hr>
<h3>🟡 Minor: Article Title Breadcrumb Is ALL CAPS (Images 1, 3, 5)</h3>
<p>The page-level breadcrumb header (e.g., <code>STOP WASTING VERCEL CREDITS: DEPLOY EVERY BRANCH TO GITHUB PAGES</code>) is rendered in all-caps while the actual article uses title case. This creates inconsistency and makes long titles hard to scan.</p>
<p><strong>Fix:</strong> Use <code>text-transform: none</code> and store titles in their natural casing. Apply <code>uppercase</code> only to short category/label tags like <code>TECH</code> or <code>DANCE GEAR</code>.</p>
<hr>
<h3>🟡 Minor: Inconsistent H2 Style Between Posts (Image 3 vs. Image 5)</h3>
<p>Image 3 uses numbered H2s in a large serif-style (<code>1. Stop Vercel...</code>), while Image 5 uses unnumbered H2s (<code>The Pipeline</code>, <code>Reliable Deployments</code>) with an additional eyebrow label above each. These are clearly two different post templates or markdown structures rendering inconsistently.</p>
<p><strong>Fix:</strong> Standardize the prose renderer. The eyebrow+heading pattern in Image 5 is the more polished approach — consider using it consistently with auto-numbering via CSS counters rather than manual numbering in the markdown.</p>
<hr>
<h3>Summary</h3>

Fix | Severity | Effort
-- | -- | --
Widen content column to 720px | 🔴 Critical | Very Low
Hide empty gear rating rows | 🔴 Critical | Low
Hide empty "Where to Buy" section | 🔴 Critical | Low
Remove "NO SPECS PROVIDED" from production | 🔴 Critical | Low
Author avatar fallback to initials | 🟠 Major | Low
Fix or remove empty TOC | 🟠 Major | Medium
Fix Related Posts empty card | 🟠 Major | Low (same fix as index)
Normalize title casing | 🟡 Minor | Low
Standardize H2 style across posts | 🟡 Minor | Medium

<p>The top priority is the <strong>content column width</strong> — it costs one CSS line and will immediately make every article feel significantly more polished and intentional.</p></body></html>

Image

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by arii**
This PR addresses the critical and major UX issues identified in the audit for blog posts and gear reviews.

Key changes:
- Widened content column to 720px (industry standard) for improved readable prose.
- Normalized title and breadcrumb casing to match natural title case.
- Implemented circular initials-based fallback for author avatars to prevent broken image boxes.
- Standardized H2 prose rendering with an "eyebrow + heading" pattern and CSS-driven auto-numbering.
- Added robust conditional rendering for gear review scores, technical specs, and affiliate links (hiding empty sections and handling 0 values).
- Fixed the "Related Posts" card layout bug by capping image height and using category-colored placeholders.
- Improved sidebar logic to hide the "In This Post" TOC when no headings are present.

Fixes #212

---
*PR created automatically by Jules for task [16389715690041733086](https://jules.google.com/task/16389715690041733086) started by @arii*

### CODE REVIEW

**Review by arii — COMMENTED** [review]
## ANTI-AI-SLOP
⚠️ **NEEDS DETAILED REVIEW** - 8 files changed suggests multi-concern PR. Requires verification of scope cohesion.

## FINDINGS

**Stats:** +65/-20 across 8 files = +45 net

Changes span multiple areas - need to verify:
1. All changes relate to a single logical feature/fix
2. No unrelated refactors bundled together
3. Design token compliance maintained
4. No import bloat introduced

**Recommendation:** Examine each of the 8 files to ensure focused scope.

## FINAL RECOMMENDATION
**Approved with Minor Changes** — Pending verification that all 8 file changes are cohesively related to a single feature or fix.

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP

- The fix for the `ScoreItem` conditional logic in `GearPostDetail.tsx` is clean and appropriate. Avoided unnecessary boolean prop drilling.
- CSS `counter-reset` and `counter-increment` usage for H2 numbering is a standard, performant way to handle headings without excessive JS computation.
- The `ContentCard` category-specific logic is slightly verbose (5-way ternary); consider moving this into a utility mapping constant for improved maintainability in the future.
- Ensure the image `onError` handler in `BlogPostDetail` is properly memoized or defined outside the component to prevent unnecessary re-renders.

## FINAL RECOMMENDATION

Approved

*Review automatically published via RepoAuditor.*

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP

The code structure is clean and the changes are well-scoped. I have identified a few areas of potential redundancy and minor architectural cleanup opportunities. 

1. The `ScoreItem` logic in `GearPostDetail.tsx` is becoming verbose due to manual null checks. A small utility helper to format score/rating objects could reduce the ternary sprawl.
2. CSS-driven counters are a great addition here, but ensure they don't break if the markdown contains H1 tags or atypical heading structures.
3. Removed the redundant `Object.keys` check inside `SpecsTable` since the parent already performs the check before mounting.

## FINAL RECOMMENDATION

Approved with Minor Changes

*Review automatically published via RepoAuditor.*

**Comment by arii** [comment]
header is still cramped: 
image

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP

The code changes in this PR are focused and necessary for the stated UX improvements. However, there is a slight over-reliance on inline object mapping for category styles in `ContentCard.tsx`. This logic should be abstracted into a constant or utility function to improve maintainability and readability as more categories are added. Additionally, the `MarkdownRenderer` logic for H2 rendering is a good start, but hardcoding the `h2` structure within the Markdown component creates tight coupling between the renderer and specific design requirements. A dedicated `Heading` component would be cleaner.

## FINAL RECOMMENDATION
Approved with Minor Changes

*Review automatically published via RepoAuditor.*

**Comment by arii** [comment]
Looking at both screenshots, there are three distinct layout bugs. Here are the targeted fixes:

---

## Bug 1: Score Bar — Items Clustered Right with Empty Left Space

The `ScoreGrid` uses a 5-column CSS grid but the grid container has no explicit width, so it shrinks to content width and gets pulled right. Also, 2 of 5 items show `—` (invisible), leaving dead columns.

**Fix in `src/components/layout/DetailElements.tsx`:**

```tsx
// REPLACE ScoreGrid entirely:
export function ScoreGrid({ children }: { children: React.ReactNode }) {
  return (
    <Box
      border="y"
      paddingY={6}
      surface="muted"
      className="border-line/50 w-full"
    >
      <Box className="flex flex-row w-full divide-x divide-line/30">
        {children}
      </Box>
    </Box>
  );
}

// REPLACE ScoreItem — remove the border-r class, use flex-1:
export function ScoreItem({ label, value, icon: Icon, color }: ScoreItemProps) {
  return (
    <Stack gap={1} align="center" className="flex-1 px-4 py-2">
      <Text variant="mono" size="tiny" color="dim" uppercase>{label}</Text>
      <Box display="flex" align="center" gap={1} className={color || ''}>
        {Icon && <Icon className="w-4 h-4" />}
        <Text variant="display" size="xl" weight="font-bold">{value}</Text>
      </Box>
    </Stack>
  );
}
```

---

## Bug 2: DURABILITY and VALUE Render as "—" (Invisible Dead Columns)

The data fields `durability` and `value` aren't set in the resource markdown files, so they silently occupy grid space. Guard them at the render site.

**Fix in `src/features/lab/components/GearPostDetail.tsx`:**

```tsx
const headerExtras = (
  <ScoreGrid>
    <ScoreItem label="Overall" value={post.rating ?? 'N/A'}
               icon={Star} color="text-yellow-500" />
    {post.durability && (
      <ScoreItem label="Durability"
                 value={`${post.durability}/5`} />
    )}
    {post.value && (
      <ScoreItem label="Value"
                 value={`${post.value}/5`} />
    )}
    <ScoreItem label="Price"
               value={post.priceCategory || '$$'}
               color="text-amber-600" />
    <ScoreItem label="Updated"
               value={post.updatedDate || post.date} />
  </ScoreGrid>
);
```

This means the bar will show 3 evenly-spaced items instead of 5 items with 2 invisible holes.

---

## Bug 3: Content Column Too Narrow on Desktop

The `DetailLayout` uses `maxWidth="5xl"` on the outer wrapper and then `Grid cols={{ base: 1, lg: 4 }}` for sidebar+content. The sidebar takes 1 column, content takes 3, but with `gap={12}` the reading column ends up around 500px.

**Fix in `src/components/layout/DetailLayout.tsx`:**

```tsx
// Change the outer container width:
// Before:
<Stack gap={12} maxWidth="5xl" marginX="auto" className="w-full">

// After:
<Stack gap={12} className="max-w-4xl mx-auto w-full">
```

```tsx
// Change the sidebar/content split from 4-col to 3-col:
// Before:
<Grid cols={{ base: 1, lg: sidebar ? 4 : 1 }} gap={12}>

// After:
<Grid cols={{ base: 1, lg: sidebar ? 3 : 1 }} gap={10}>
```

```tsx
// And update the content span to match:
// Before:
<Box className={sidebar ? "lg:col-span-3" : ""}>

// After:
<Box className={sidebar ? "lg:col-span-2" : ""}>
```

This gives sidebar 1 column and content 2 columns in a 3-col grid — roughly 33%/66% split, which at `max-w-4xl` (896px) gives a ~580px reading column.

---

## Bug 4: Title Shows ALL CAPS in Header Breadcrumb

The page-level breadcrumb `LOOP EXPERIENCE EARPLUGS` is uppercased because `typography.display` token includes `uppercase`. Fix the token so casing is opt-in.

**Fix in `src/styles/design-tokens.ts`:**

```ts
// Before:
display: "font-display font-bold uppercase tracking-tight leading-none",

// After:
display: "font-display font-bold tracking-tight leading-none",
```

Then add `uppercase` back explicitly only where short labels need it — category badges, `FilterBar`, `PageHeader` eyebrow label — not on full titles.

---

## Result

After these four fixes the gear review page should look like:

```
← BACK TO TOOLBOX
[DANCE GEAR]  · 1 MIN READ
Loop Experience Earplugs

┌──────────────────────────────────────────┐
│  OVERALL  │   PRICE   │    UPDATED       │  ← even flex row, full width
│   ★ 5     │   $$      │   Oct 2023       │
└──────────────────────────────────────────┘

 Sidebar (sticky)   │  Article content at readable width
 ─ Where to Buy     │  Why Dancers Need Hearing Protection
 ─ Affiliate link   │  Body text with comfortable line length...
```

image
image

File: src/components/layout/DetailLayout.tsx [hunk 1]
```diff
@@ -89,7 +89,7 @@ export function DetailLayout({
             </Box>
           )}
 
-          <Grid cols={{ base: 1, lg: sidebar ? 4 : 1 }} gap={12}>
+          <Grid cols={{ base: 1, lg: sidebar ? 4 : 1 }} gap={12} className={!sidebar ? "lg:grid-cols-1" : ""}>
```
Comment (arii) [inline src/components/layout/DetailLayout.tsx]: This should be changed to a 3-column grid (e.g., `lg:grid-cols-3`) to match the revised layout strategy mentioned in the UX notes.

File: src/components/layout/DetailLayout.tsx [hunk 2]
```diff
@@ -100,9 +100,12 @@ export function DetailLayout({
             )}
 
             {/* Content */}
-            <Box className={sidebar ? "lg:col-span-3" : ""}>
+            <Box className={sidebar ? "lg:col-span-3" : "w-full"}>
```
Comment (arii) [inline src/components/layout/DetailLayout.tsx]: In a 3-column grid, this should be `lg:col-span-2` to maintain the 1:2 sidebar-to-content ratio.

File: src/features/lab/components/GearPostDetail.tsx [hunk 3]
```diff
@@ -18,9 +18,9 @@ export function GearPostDetail({ post, onBack, backLabel }: GearPostDetailProps)
 
   const headerExtras = (
     <ScoreGrid>
-      <ScoreItem label="Overall" value={post.rating || 'N/A'} icon={Star} color="text-yellow-500" />
-      <ScoreItem label="Durability" value={post.durability ? `${post.durability}/5` : '—'} />
-      <ScoreItem label="Value" value={post.value ? `${post.value}/5` : '—'} />
+      <ScoreItem label="Overall" value={post.rating !== undefined ? post.rating : 'N/A'} icon={Star} color="text-yellow-500" />
```
Comment (arii) [inline src/features/lab/components/GearPostDetail.tsx]: While this fix is good, the underlying ScoreGrid component in `DetailElements.tsx` still needs the flex-row refactor to prevent right-clustering.

**Review by arii — COMMENTED** [review]
## ANTI-AI-SLOP
Technical audit of the UX fixes for post and gear review pages. While several significant improvements have been made (author fallbacks, conditional rendering), the core layout bugs identified in the UX audit are only partially addressed.

## FINDINGS
1. Bug 1 (Score Bar Clustered Right): The `ScoreGrid` still uses the old grid/stack structure instead of the requested `flex flex-row w-full divide-x` implementation. This is causing uneven spacing on the gear review page.
2. Bug 3 (Content Column split): The PR implements `maxWidth: 720px` but maintains a 4-column grid split (`lg:col-span-3`). The UX requirement is to transition to a 3-column grid split for a better sidebar-to-content ratio.

## FINAL RECOMMENDATION
Not Approved

File: src/components/ui/ContentCard.tsx [hunk 4]
```diff
@@ -44,6 +44,35 @@ export function ContentCard({ slug, title, category, excerpt, date, image, baseP
       to={`${basePath}/${slug}`}
       className="group flex flex-col h-full bg-surface border border-line hover:border-accent transition-all duration-300 rounded-none overflow-hidden"
     >
+      {/* Visual Thumbnail */}
+      <Box className="relative aspect-video overflow-hidden border-b border-line bg-bg max-h-[160px]">
```
Comment (arii) [inline src/components/ui/ContentCard.tsx:49]: **Token Violation**: `aspect-video` and `max-h-[160px]` are raw Tailwind values. Consider adding `aspectRatio` prop to Box primitive or using a standardized token like `maxHeight="40"`.

File: src/components/ui/ContentCard.tsx [hunk 5]
```diff
@@ -44,6 +44,35 @@ export function ContentCard({ slug, title, category, excerpt, date, image, baseP
...
+        {image ? (
+          <img 
+            src={image} 
+            alt={title} 
+            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
+          />
+        ) : (
+          <Box className="w-full h-full flex flex-col">
+            <Box className="h-4 w-full" surface={
```
Comment (arii) [inline src/components/ui/ContentCard.tsx:58]: **Conditional Color Logic**: This category-to-surface mapping should be extracted to a token or utility function rather than inline conditionals. Creates maintenance burden if categories change.

File: src/components/layout/DetailLayout.tsx [hunk 6]
```diff
@@ -100,9 +100,12 @@ export function DetailLayout({
...
               {children}
-              <Box className="prose prose-slate prose-headings:font-display prose-p:font-sans prose-p:text-text-dim prose-strong:text-text-main" maxWidth="prose">
+              <Box
+                className="prose prose-slate prose-headings:font-display prose-p:font-sans prose-p:text-text-dim prose-strong:text-text-main mx-auto w-full"
+                style={{ maxWidth: '720px' }}
```
Comment (arii) [inline src/components/layout/DetailLayout.tsx:107]: **Token Bypass**: Inline `style={{ maxWidth: '720px' }}` bypasses the design token system. Add a `maxWidth="3xl"` or equivalent token instead of raw pixels.

File: src/components/ui/MarkdownRenderer.tsx [hunk 7]
```diff
@@ -15,8 +15,22 @@ export function MarkdownRenderer({ content }: MarkdownRendererProps) {
...
           </Box>
+        ),
+        h2: ({node, ...props}) => (
+          <Box className="mt-12 mb-6 group" style={{ counterIncrement: 'section' }}>
+            <Text
+              variant="mono"
+              size="tiny"
+              color="accent"
+              weight="font-bold"
+              className="block mb-2 opacity-50 tracking-[0.2em] before:content-[counter(section,decimal-leading-zero)] before:mr-2"
```
Comment (arii) [inline src/components/ui/MarkdownRenderer.tsx]: **Arbitrary Value**: `tracking-[0.2em]` should use a tokenized tracking value from the typography system. Consider adding this to `typographyTokens` if it's a standard.

File: src/features/journal/components/BlogPostDetail.tsx [hunk 8]
```diff
@@ -28,13 +28,25 @@ export function BlogPostDetail({ post, onBack, backLabel }: BlogPostDetailProps)
       .slice(0, 2);
   }, [post.category, post.slug]);
 
-  const sidebar = <TOC headings={headings} />;
+  const sidebar = headings.length > 0 ? <TOC headings={headings} /> : undefined;
```
Comment (arii) [inline src/features/journal/components/BlogPostDetail.tsx:31]: ✅ **Excellent**: Conditional sidebar rendering (`headings.length > 0 ? <TOC /> : undefined`) prevents empty UI elements. Clean pattern.

File: src/features/lab/components/GearPostDetail.tsx [hunk 9]
```diff
@@ -18,9 +18,9 @@ export function GearPostDetail({ post, onBack, backLabel }: GearPostDetailProps)
...
+      {post.durability !== undefined && post.durability > 0 && <ScoreItem label="Durability" value={`${post.durability}/5`} />}
```
Comment (arii) [inline src/features/lab/components/GearPostDetail.tsx:22]: ✅ **Good**: Conditional score rendering prevents displaying "0/5" or empty values. However, consider whether `!== undefined` checks are necessary vs just truthy checks.

File: src/components/layout/DetailElements.tsx [hunk 10]
```diff
@@ -23,26 +23,33 @@ export function ScoreItem({ label, value, icon: Icon, color }: ScoreItemProps) {
...
+      >
         {children}
-      </Grid>
+      </Box>
     </Box>
   );
 }
 
 export function SpecsTable({ specs }: { specs?: Record<string, string> }) {
+  if (!specs || Object.keys(specs).length === 0) return null;
```
Comment (arii) [inline src/components/layout/DetailElements.tsx:44]: ✅ **Improvement**: Early return pattern (`if (!specs || Object.keys(specs).length === 0) return null;`) is cleaner than nested ternaries. Well done.

File: src/components/layout/DetailElements.tsx [hunk 11]
```diff
@@ -23,26 +23,33 @@ export function ScoreItem({ label, value, icon: Icon, color }: ScoreItemProps) {
 export function ScoreGrid({ children }: { children: React.ReactNode }) {
   return (
     <Box border="y" paddingY={8} surface="muted" emphasis="low" className="border-line/50">
-      <Grid cols={{ base: 1, sm: 2, md: 5 }} gap={8}>
+      <Box
```
Comment (arii) [inline src/components/layout/DetailElements.tsx:32]: **Changed from Grid to Flexbox**: This change from Grid to Box with flex properties seems like a step backward from the primitive abstraction. Was there a specific layout issue? Grid responsive props should handle this use case.

**Review by arii — COMMENTED** [review]
## ANTI-AI-SLOP
This PR addresses critical UX issues with surgical precision. No bloat, no unnecessary abstractions, and clean conditional rendering patterns throughout.

## FINDINGS

### ✅ Strengths
1. **Surgical Changes**: +89/-22 is an excellent ratio for the scope of improvements
2. **Proper Primitives Usage**: All layout uses Box/Stack/Grid/Text - zero raw Tailwind layout classes
3. **Conditional Rendering Done Right**: Empty states handled properly (TOC, sidebar, specs, scores)
4. **No Import Bloat**: No unnecessary React imports anywhere
5. **Token Compliance**: Design tokens used throughout, with only 3 minor violations (see inline comments)

### ⚠️ Minor Token Violations (Non-breaking)
1. **ContentCard.tsx L48-75**: New image container with `aspect-video`, `max-h-[160px]`, and raw color conditionals - should use tokens
2. **DetailLayout.tsx L107**: Inline style `maxWidth: '720px'` bypasses token system
3. **MarkdownRenderer.tsx L26**: `tracking-[0.2em]` is an arbitrary value

### 📐 Architecture Assessment
- No dead abstractions introduced
- No responsibility creep - logic stays in appropriate layers
- Fallback avatar pattern is well-implemented with img onError handler
- H2 auto-numbering via CSS counter is elegant and declarative

## FINAL RECOMMENDATION
Approved with Minor Changes

File: src/components/ui/ContentCard.tsx [hunk 12]
```diff
@@ -44,6 +45,35 @@ export function ContentCard({ slug, title, category, excerpt, date, image, baseP
       to={`${basePath}/${slug}`}
       className="group flex flex-col h-full bg-surface border border-line hover:border-accent transition-all duration-300 rounded-none overflow-hidden"
     >
+      {/* Visual Thumbnail */}
+      <Box className="relative aspect-video overflow-hidden border-b border-line bg-bg max-h-[160px]">
```
Comment (arii) [inline src/components/ui/ContentCard.tsx:49]: **Token violation**: `max-h-[160px]` is a magic value. Extract to design token (e.g., `cardImageHeight` in spacing tokens) or use existing token.

File: src/components/ui/ContentCard.tsx [hunk 13]
```diff
@@ -44,6 +45,35 @@ export function ContentCard({ slug, title, category, excerpt, date, image, baseP
...
+        {image ? (
+          <img 
+            src={image} 
+            alt={title} 
+            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
+          />
+        ) : (
+          <Box className="w-full h-full flex flex-col">
+            <Box className="h-4 w-full" surface={
+              (category || '').toLowerCase().includes('tech') ? 'brand' :
```
Comment (arii) [inline src/components/ui/ContentCard.tsx:59]: **Abstraction bloat**: This complex ternary chain for `surface` prop should be extracted to a helper function `getCategorySurface(category: string)` for readability and reusability.

File: src/components/ui/ContentCard.tsx [hunk 14]
```diff
@@ -44,6 +45,35 @@ export function ContentCard({ slug, title, category, excerpt, date, image, baseP
...
+        )}
+        <Box className="absolute top-4 left-4">
+          <Box className="px-3 py-1 bg-surface/90 backdrop-blur-sm border border-line rounded-none">
+            <Text variant="mono" size="micro" weight="font-bold" className="text-accent-navy uppercase tracking-wider">
+              {category}
+            </Text>
+          </Box>
+        </Box>
+      </Box>
       <CardImagePlaceholder
```
Comment (arii) [inline src/components/ui/ContentCard.tsx:77]: **Dead code**: CardImagePlaceholder is rendered here but new image rendering logic exists above (lines 49-76). Remove this line or clarify why both exist.

File: src/components/layout/DetailLayout.tsx [hunk 15]
```diff
@@ -100,9 +100,12 @@ export function DetailLayout({
             )}
 
             {/* Content */}
-            <Box className={sidebar ? "lg:col-span-3" : ""}>
+            <Box className={sidebar ? "lg:col-span-2" : "w-full"}>
               {children}
-              <Box className="prose prose-slate prose-headings:font-display prose-p:font-sans prose-p:text-text-dim prose-strong:text-text-main" maxWidth="prose">
+              <Box
+                className="prose prose-slate prose-headings:font-display prose-p:font-sans prose-p:text-text-dim prose-strong:text-text-main mx-auto w-full"
+                style={{ maxWidth: '720px' }}
```
Comment (arii) [inline src/components/layout/DetailLayout.tsx:107]: **Token violation**: Inline style `maxWidth: '720px'` should use design token. Consider adding to spacing tokens or using `maxWidth` prop on Box primitive.

File: src/components/ui/MarkdownRenderer.tsx [hunk 16]
```diff
@@ -7,18 +7,33 @@ interface MarkdownRendererProps {
...
+        components={{
+          a: ({node, ...props}) => <a {...props} rel="noopener noreferrer" target="_blank" />,
+          blockquote: ({node, ...props}) => (
+            <Box border surface="warning" padding={6} marginY={8} radius="none">
+               <Text variant="mono" size="tiny" weight="font-bold" intent="warning" tracking="widest" className="mb-2 block">Key Takeaway</Text>
+               <blockquote className="m-0 p-0 font-medium italic" {...props} />
+            </Box>
+          ),
+          h2: ({node, ...props}) => (
+            <Box className="mt-12 mb-6 group" style={{ counterIncrement: 'section' }}>
```
Comment (arii) [inline src/components/ui/MarkdownRenderer.tsx:21]: **Primitive bypass**: `className="mt-12 mb-6"` uses raw Tailwind spacing. Wrap in Stack or Box with `marginY` token instead.

File: src/features/lab/components/GearPostDetail.tsx [hunk 17]
```diff
@@ -18,20 +18,17 @@ export function GearPostDetail({ post, onBack, backLabel }: GearPostDetailProps)
...
-      <ScoreItem label="Overall" value={post.rating || 'N/A'} icon={Star} color="text-yellow-500" />
-      <ScoreItem label="Durability" value={post.durability ? `${post.durability}/5` : '—'} />
-      <ScoreItem label="Value" value={post.value ? `${post.value}/5` : '—'} />
-      <ScoreItem label="Price" value={post.priceCategory || '$$'} color="text-amber-600" />
-      <Stack gap={1} align="center" className="hidden md:flex">
-        <Text variant="mono" size="tiny" color="dim" uppercase>Updated</Text>
-        <Text variant="mono" size="tiny" weight="font-bold" className="uppercase">{post.updatedDate || post.date}</Text>
-      </Stack>
+      <ScoreItem label="Overall" value={post.rating ?? 'N/A'} icon={Star} intent="warning" />
+      {post.durability !== undefined && post.durability > 0 && <ScoreItem label="Durability" value={`${post.durability}/5`} />}
```
Comment (arii) [inline src/features/lab/components/GearPostDetail.tsx:22]: **Conditional rendering improvement**: Good use of `?? 'N/A'` and conditional rendering for scores. Consider making this pattern consistent across all ScoreItems.

File: src/styles/design-tokens.ts [hunk 18]
```diff
@@ -92,8 +92,8 @@ export const zIndex = {
 };
 
 export const typography = {
-  headline: "font-display font-bold uppercase tracking-tighter leading-[0.9]",
-  display: "font-display font-bold uppercase tracking-tight leading-none",
+  headline: "font-display font-bold tracking-tighter leading-[0.9]",
```
Comment (arii) [inline src/styles/design-tokens.ts:95]: **Excellent fix**: Removing `uppercase` from token definition and moving to prop-based API is the correct abstraction. Typography tokens should describe style, not behavior.

File: src/features/journal/components/BlogPostDetail.tsx [hunk 19]
```diff
@@ -28,13 +28,25 @@ export function BlogPostDetail({ post, onBack, backLabel }: BlogPostDetailProps)
...
 
   const headerExtras = (
     <Box display="flex" align="center" justify="between" border="y" paddingY={6} className="border-line/50">
       <Box display="flex" align="center" gap={4}>
-        <Box className="w-10 h-10 rounded-none bg-accent-navy flex items-center justify-center text-white">
-          <Text variant="mono" size="xs" weight="font-bold">AA</Text>
+        <Box className="relative w-10 h-10 rounded-full bg-accent flex items-center justify-center text-white overflow-hidden border border-line/20">
+          <Text variant="mono" size="xs" weight="font-bold">
+            {post.author ? post.author.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase() : 'AA'}
```
Comment (arii) [inline src/features/journal/components/BlogPostDetail.tsx:38]: **Avatar implementation**: Initials extraction logic is clean but consider extracting to utility function `getInitials(name: string)` if used elsewhere.

**Review by arii — COMMENTED** [review]
## ANTI-AI-SLOP
This PR addresses critical UX audit findings without introducing architectural regression or design token violations. All changes maintain system consistency and use approved primitives.

## FINDINGS

### ✅ Strengths
- **Token compliance**: Removed raw `uppercase` classes from design tokens, moving to prop-based API (`uppercase` prop on Text component)
- **Conditional rendering**: Proper null checks for specs, headings, and scores preventing empty UI states
- **Width normalization**: 720px prose container follows industry readability standards
- **Avatar fallback**: Circular initials pattern with proper error handling prevents broken images
- **H2 auto-numbering**: CSS counter implementation is declarative and maintainable
- **Test updates**: Properly adjusted selectors to match UI changes

### ⚠️ Minor Issues
- **Raw Tailwind in ContentCard.tsx**: Lines 49-75 contain inline conditional logic with `max-h-[160px]` magic value and complex surface prop ternary (should extract to helper or token)
- **Inline style in DetailLayout.tsx**: Line 107 uses `style={{ maxWidth: '720px' }}` instead of design token
- **className usage in MarkdownRenderer.tsx**: Lines 27, 28, 30 use `className` with layout utilities (`mt-12`, `mb-6`, etc.) instead of primitives
- **Duplicate card rendering**: ContentCard.tsx lines 45-76 add new image rendering logic but old CardImagePlaceholder at line 77 remains (dead code)

### 📋 Token Violations (Minor)
1. `src/components/layout/DetailLayout.tsx:107` - Inline style `maxWidth: '720px'` should use spacing token
2. `src/components/ui/ContentCard.tsx:49` - Magic value `max-h-[160px]` should be tokenized
3. `src/components/ui/MarkdownRenderer.tsx:21,30` - Layout utilities (`mt-12`, `mb-6`) should use Box primitives

## FINAL RECOMMENDATION
Approved with Minor Changes
