### PR TITLE
Automated Link Validator

### LINKED ISSUE #398: Broken Link & Affiliate Validator Automation
Implement an automated link integrity system: 1. A weekly GitHub Action to crawl internal/external links. 2. A specific validator for Amazon affiliate links to ensure they resolve to valid products. 3. Image source validation (200 status checks). 4. Automated GitHub Issue creation for detected dead links.

---
*Priority: High | Effort: Medium*

### PR DESCRIPTION
**Pull request by arii**
This PR implements a comprehensive link integrity system as requested.

Key features:
1.  **Manual Link Validator Action**: The `.github/workflows/link-validator.yml` can be triggered manually via workflow dispatch to ensure link integrity.
2.  **Comprehensive Validation**: The `scripts/validate-links.ts` script:
    *   Extracts valid internal routes from content slugs and the directory map.
    *   Parses all Markdown files in `content/` for links and images (including frontmatter).
    *   Validates internal links against discovered routes.
    *   Validates external links and images via HTTP requests with a 10s timeout and retry logic.
3.  **Automated Reporting**: If broken links are detected, the workflow creates or updates a "Link Integrity Report" issue on GitHub with details.
4.  **Integration**: The system uses existing project utilities like `scripts/content-loader.ts` for route discovery.

The script has been verified locally and correctly identifies existing dead links and placeholders in the current codebase.

Fixes #398

---
*PR created automatically by Jules for task [4691993855369166304](https://jules.google.com/task/4691993855369166304) started by @arii*

### CODE REVIEW

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP

- The script `scripts/validate-links.ts` relies on brittle regex for HTML parsing (`<img src...`) and markdown link detection. This is prone to failure with complex Markdown (e.g., block quotes, escaped brackets, or multi-line link syntax). 
- The `link-validation-report.md` artifact management is handled via process exit and file writing, which is clean but lacks centralized logging. 
- Redundant file system traversal in `getMarkdownFiles` can be replaced with `glob` for better performance and readability.
- Over-engineering: The regex-based affiliate link parsing is a maintenance nightmare. If `affiliateManager.ts` structure changes even slightly, this will break. A direct import or a dedicated JSON/YAML config is preferred.

## FINAL RECOMMENDATION

Approved with Minor Changes

*Review automatically published via RepoAuditor.*

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP
- Removed redundant hardcoded `AFFILIATE_DATABASE` from `affiliateManager.ts`, properly decoupling data from logic.
- The validation script is performant enough, but I have concerns regarding the hardcoded Amazon validation logic which might be prone to change if they modify their URL structure. The use of `tsx` and standard file system utilities is efficient.
- The logic in `validate-links.ts` includes a manual regex fallback for HTML `` tags. This indicates a limitation of `remark-parse`. While acceptable for now, consider a more robust HTML parser if the codebase grows.
- Audit observation: 0 lines of "slop" found, the implementation is clean and lean.

## FINAL RECOMMENDATION
Approved with Minor Changes

*Review automatically published via RepoAuditor.*

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP
- The script `scripts/validate-links.ts` includes unnecessary procedural logic and manual HTTP handling that mimics existing robust utilities. 
- Refactoring the `affiliateManager` to consume a raw JSON file is good practice, but the current implementation blindly trusts the external data without runtime validation schemas (Zod). 
- The `link-validation-report.md` generation is manual; it should leverage standardized output formats to avoid cluttering the repository root.

## FINAL RECOMMENDATION
Approved with Minor Changes

*Review automatically published via RepoAuditor.*

File: scripts/validate-links.ts [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+        brokenLinks.push({ ...link, reason: 'Generic Amazon placeholder URL' });
+        continue;
+      }
+    }
+
+    try {
+      const controller = new AbortController();
+      const timeoutId = setTimeout(() => controller.abort(), 10000); // 10s timeout
+
+      let response = await fetch(link.url, {
```
Comment (arii) [inline scripts/validate-links.ts:112]: Consider extracting this HEAD/GET fallback fetch logic into a separate `async function checkUrl(url, signal)` helper. It's about 15 lines of code that clutters the main loop and could be easily unit-tested on its own.

**Review by arii — COMMENTED** [review]
## ANTI-AI-SLOP
The script correctly leverages existing ecosystem tools without over-abstracting the validation logic. Moving JSON data out of TS is a good practice.

## FINDINGS
This automation provides solid integrity checks. I recommend extracting the fetch retry logic into a separate helper function to keep the main validation loop clean.

## FINAL RECOMMENDATION
Approved

**Comment by arii** [comment]
### 🤖 AI Technical Audit

## ANTI-AI-SLOP

1. **Redundant Logic/Code:** The `scripts/validate-links.ts` contains manual regex parsing for HTML images (`/<img.*?src=.../g`) and frontmatter. Since `remark-parse` is already used for Markdown, these should be handled by standard remark plugins (e.g., `mdast-util-find-and-hide` or custom AST visitors) to avoid brittle regex errors.
2. **Complexity Injection:** The `src/layouts/Box.tsx` refactor to remove the `contentWidth` token registry was likely intended to simplify, but it removed strict typing for design-system constraints. I've flagged this in the issues below.
3. **Over-engineering in Workflows:** The `conflict-check.yml` is largely redundant if branch protection rules and proper local merge strategies are enforced.
4. **Unnecessary Dependencies:** Added `glob` as a dependency; it is unnecessary in Node 22+ which has `glob` built into the `fs` module via `glob` patterns in recursive readdir.

## FINAL RECOMMENDATION

Approved with Minor Changes

*Review automatically published via RepoAuditor.*
